"""Emit LaTeX tables from results/metrics.json, for report/main.tex.

Regenerating the tables from the metrics file means the report can never drift
from the run that produced it -- there is no hand-copied number anywhere.

    python tools/make_report_tables.py
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import numpy as np  # noqa: E402

from utils import load_json  # noqa: E402

TABLE_DIR = REPO / "report" / "tables"

MAIN_ROWS = [
    ("baseline_b1_random", "B1: Random tags"),
    ("baseline_b1_prior", "B1: Tag prior"),
    ("baseline_b2_melcnn", "B2: CNN mel-spectrogram"),
    ("baseline_b4_pca_mlp", "B4: PCA + MLP"),
    ("task1_bert", "Task 1: BERT-only"),
    ("task2_gnn_sage", "Task 2: GNN-only (GraphSAGE)"),
    ("task2_gnn_gat", "Task 2: GNN-only (GAT)"),
    ("task3_fusion_cross_attention", "Task 3: GNN--BERT (cross-attn)"),
    ("task4_contrastive", "Task 4: Contrastive dual encoder"),
]

ABLATION_ROWS = [
    ("task3_fusion_bert_only", "BERT-only"),
    ("task3_fusion_gnn_only", "GNN-only"),
    ("task3_fusion_concat", "Early concatenation"),
    ("task3_fusion_cross_attention", "Cross-attention (full)"),
]


def fmt(value, digits: int = 3) -> str:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        return "--"
    if not np.isfinite(value):
        return "--"
    return f"{value:.{digits}f}"


def escape(text: str) -> str:
    return str(text).replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def main_table(metrics: dict) -> str:
    lines = [
        r"% Auto-generated by tools/make_report_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Model comparison on the held-out test split. Thresholds are"
        r" tuned on validation and applied unchanged to test. Macro-F1 excludes"
        r" tags with no positives in the split.}",
        r"\label{tab:main-results}",
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        r"Model & Macro-F1 & Micro-F1 & AUC-PR & MAE (emotion) & R@5 \\",
        r"\midrule",
    ]
    for key, label in MAIN_ROWS:
        m = metrics.get(key)
        if not isinstance(m, dict):
            continue
        lines.append(
            f"{escape(label)} & {fmt(m.get('macro_f1'))} & {fmt(m.get('micro_f1'))} "
            f"& {fmt(m.get('auc_pr'))} & {fmt(m.get('mae_mean'))} "
            f"& {fmt(m.get('mean_R@5'))} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def ablation_table(metrics: dict) -> str:
    lines = [
        r"% Auto-generated by tools/make_report_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Task 3 fusion ablation. All arms share the same encoders,"
        r" loss, schedule and seed; only the fusion operator changes.}",
        r"\label{tab:ablation}",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"Fusion arm & Macro-F1 & Micro-F1 & AUC-PR & MAE (emotion) \\",
        r"\midrule",
    ]
    for key, label in ABLATION_ROWS:
        m = metrics.get(key)
        if not isinstance(m, dict):
            continue
        lines.append(
            f"{escape(label)} & {fmt(m.get('macro_f1'))} & {fmt(m.get('micro_f1'))} "
            f"& {fmt(m.get('auc_pr'))} & {fmt(m.get('mae_mean'))} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def retrieval_table(metrics: dict) -> str:
    m = metrics.get("task4_contrastive")
    lines = [
        r"% Auto-generated by tools/make_report_tables.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Cross-modal retrieval on the test split (Task 4), with"
        r" zero-shot tagging transferred from the same encoders.}",
        r"\label{tab:retrieval}",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Direction & R@1 & R@5 & R@10 \\",
        r"\midrule",
    ]
    if isinstance(m, dict):
        for key, label in (("audio2caption", "Audio $\\rightarrow$ Caption"),
                           ("caption2audio", "Caption $\\rightarrow$ Audio")):
            lines.append(
                f"{label} & {fmt(m.get(f'{key}_R@1'))} & {fmt(m.get(f'{key}_R@5'))} "
                f"& {fmt(m.get(f'{key}_R@10'))} \\\\")
        lines += [
            r"\midrule",
            f"Zero-shot tagging (Macro-F1) & \\multicolumn{{3}}{{c}}"
            f"{{{fmt(m.get('zero_shot_macro_f1'))}}} \\\\",
        ]
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def dataset_table(metrics: dict | None = None) -> str:
    """Describe the corpus the numbers came from.

    Prefers the `_provenance` recorded in metrics.json over whatever is in
    data/processed/, because that directory is overwritten by the next corpus
    preprocessed -- reading it can describe a different corpus than the table.
    """
    prov = (metrics or {}).get("_provenance") or {}
    meta_path = REPO / "data" / "processed" / "meta.json"
    disk = load_json(meta_path) if meta_path.exists() else {}
    if not prov and not disk:
        return "% run src/preprocess.py first\n"

    def field(key, default="?"):
        return prov.get(key, disk.get(key, default))

    rows = [
        ("Source", escape(field("corpus", field("source")))),
        ("Tracks", field("n_tracks")),
        ("Graph kind", escape(field("graph_kind"))),
        ("Segment length (s)", field("segment_seconds")),
        ("Avg.\\ nodes / graph", disk.get("avg_nodes", "?")),
        ("Avg.\\ edges / graph", disk.get("avg_edges", "?")),
        ("Node feature dim", disk.get("node_feature_dim", "?")),
        ("Tag vocabulary", field("num_tags")),
        ("Text encoder", escape(field("text_model"))),
        ("Split strategy", escape(field("split_strategy"))),
        ("Train / val / test", " / ".join(
            str((field("split_sizes") or {}).get(s, "?"))
            for s in ("train", "val", "test"))),
    ]
    lines = [
        r"% Auto-generated by tools/make_report_tables.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering",
        r"\caption{Dataset and preprocessing configuration for the reported run.}",
        r"\label{tab:dataset}",
        r"\begin{tabular}{ll}", r"\toprule",
        r"Property & Value \\", r"\midrule",
    ]
    lines += [f"{k} & {v} \\\\" for k, v in rows]
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    import argparse

    ap = argparse.ArgumentParser(description="Emit LaTeX tables from a metrics file.")
    ap.add_argument("--results", default="results",
                    help="results directory holding metrics.json (e.g. results_mtat)")
    ap.add_argument("--out", default=None, help="output dir (default report/tables)")
    args = ap.parse_args()

    global TABLE_DIR
    if args.out:
        TABLE_DIR = Path(args.out)

    results_dir = Path(args.results)
    if not results_dir.is_absolute():
        results_dir = REPO / results_dir
    metrics_path = results_dir / "metrics.json"
    if not metrics_path.exists():
        raise SystemExit(f"No {metrics_path} -- run src/train.py first.")
    metrics = load_json(metrics_path)

    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    outputs = {
        "main_results.tex": main_table(metrics),
        "ablation.tex": ablation_table(metrics),
        "retrieval.tex": retrieval_table(metrics),
        "dataset.tex": dataset_table(metrics),
    }
    for name, content in outputs.items():
        (TABLE_DIR / name).write_text(content, encoding="utf-8")
        print(f"wrote {(TABLE_DIR / name)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
