"""Emit the two report tables that span more than one results directory.

`make_report_tables.py` reads a single metrics.json, which is right for the
main comparison and the ablation. Two tables in the report are cross-run by
nature and need their own generator:

  graph_kinds.tex  segment vs chord vs hybrid -- three separate preprocessing
                   runs, so three results directories
  gtzan.tex        Task 2's headline result, which lives on a different corpus
                   from the Task 1/3/4 table and must never be merged with it

    python tools/make_extra_tables.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

TABLE_DIR = REPO / "report" / "tables"

GRAPH_KINDS = [
    ("Segment (temporal + similarity)", "results_gtzan", "data/processed_gtzan"),
    ("Chord transition", "results_gtzan_chord", "data/processed_gtzan_chord"),
    ("Hybrid (segment + chord)", "results_gtzan_hybrid", "data/processed_gtzan_hybrid"),
]

GTZAN_ROWS = [
    ("baseline_b1_random", "B1: Random"),
    ("baseline_b1_prior", "B1: Genre prior"),
    ("baseline_b2_melcnn", "B2: CNN mel-spectrogram"),
    ("baseline_b4_pca_mlp", "B4: PCA + MLP"),
    ("task2_gnn_sage", "Task 2: GNN (GraphSAGE)"),
    ("task2_gnn_gat", "Task 2: GNN (GAT)"),
]


def load(results: str, key: str) -> dict | None:
    p = REPO / results / "metrics.json"
    if not p.exists():
        return None
    return json.load(open(p, encoding="utf-8")).get(key)


def graph_kind_table() -> str | None:
    rows = []
    for label, res, proc in GRAPH_KINDS:
        m = load(res, "task2_gnn_sage")
        meta_path = REPO / proc / "meta.json"
        if not m or not meta_path.exists():
            print(f"  skipping {label}: no results at {res}")
            continue
        meta = json.load(open(meta_path, encoding="utf-8"))
        rows.append(f"{label} & {meta['avg_nodes']:.1f} & {meta['avg_edges']:.1f} & "
                    f"{m['macro_f1']:.3f} & {m['micro_f1']:.3f} & {m['auc_pr']:.3f} \\\\")
    if len(rows) < 2:
        return None
    return "\n".join([
        r"% Auto-generated by tools/make_extra_tables.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering",
        r"\caption{Graph construction compared on Task 2 (GTZAN genre "
        r"classification). Identical encoder, schedule and seed; only the graph "
        r"differs. Nodes and edges are per-clip means.}",
        r"\label{tab:graph-kinds}",
        r"\begin{tabular}{lccccc}", r"\toprule",
        r"Graph & Nodes & Edges & Macro-F1 & Micro-F1 & AUC-PR \\", r"\midrule",
        *rows, r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])


def gtzan_table() -> str | None:
    rows = []
    for key, label in GTZAN_ROWS:
        m = load("results_gtzan", key)
        if not m:
            continue
        rows.append(f"{label} & {m['macro_f1']:.3f} & {m['micro_f1']:.3f} & "
                    f"{m['auc_pr']:.3f} \\\\")
    if not rows:
        return None
    meta_path = REPO / "data" / "processed_gtzan" / "meta.json"
    meta = json.load(open(meta_path, encoding="utf-8")) if meta_path.exists() else {}
    split = meta.get("split_sizes", {})
    caption = (r"\caption{Task 2 --- genre classification on GTZAN ("
               f"{meta.get('n_tracks', '?')} clips, {meta.get('num_tags', '?')} genres, "
               f"artist-grouped split {split.get('train','?')}/{split.get('val','?')}/"
               f"{split.get('test','?')}). B2 consumes the same per-segment features as "
               r"the GNN, so the gap between them isolates relational structure.}")
    return "\n".join([
        r"% Auto-generated by tools/make_extra_tables.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering", caption,
        r"\label{tab:gtzan}",
        r"\begin{tabular}{lccc}", r"\toprule",
        r"Model & Macro-F1 & Micro-F1 & AUC-PR \\", r"\midrule",
        *rows, r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])


def main() -> int:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in (("graph_kinds.tex", graph_kind_table()),
                          ("gtzan.tex", gtzan_table())):
        if content is None:
            print(f"  {name}: not enough data, skipped")
            continue
        (TABLE_DIR / name).write_text(content, encoding="utf-8")
        print(f"wrote {TABLE_DIR / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
